#
# Arm SCP/MCP Software
# Copyright (c) 2022, Linaro Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := VRING_MHU
BS_LIB_SOURCES = mod_vring_mhu.c

include $(BS_DIR)/lib.mk
