#
# Arm SCP/MCP Software
# Copyright (c) 2022, Linaro Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := VIRTIO_SMT
BS_LIB_SOURCES = mod_virtio_smt.c

include $(BS_DIR)/lib.mk
